// <auto-generated />
using System;
using System.Collections.Generic;
using Mappa.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace mappa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250221111857_FormerReligionAndCopiesRefactor")]
    partial class FormerReligionAndCopiesRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityWrittenSource", b =>
                {
                    b.Property<int>("CitiesMentionedByTheSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesMentioningTheCityId")
                        .HasColumnType("integer");

                    b.HasKey("CitiesMentionedByTheSourceId", "SourcesMentioningTheCityId");

                    b.HasIndex("SourcesMentioningTheCityId");

                    b.ToTable("CityWrittenSource");
                });

            modelBuilder.Entity("CityWrittenSource1", b =>
                {
                    b.Property<int>("CitiesWhereSourcesAreWrittenId")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesWrittenInTheCityId")
                        .HasColumnType("integer");

                    b.HasKey("CitiesWhereSourcesAreWrittenId", "SourcesWrittenInTheCityId");

                    b.HasIndex("SourcesWrittenInTheCityId");

                    b.ToTable("CityWrittenSource1");
                });

            modelBuilder.Entity("LanguageSecondarySource", b =>
                {
                    b.Property<int>("SecondarySourceId")
                        .HasColumnType("integer");

                    b.Property<int>("TranslatedLanguagesId")
                        .HasColumnType("integer");

                    b.HasKey("SecondarySourceId", "TranslatedLanguagesId");

                    b.HasIndex("TranslatedLanguagesId");

                    b.ToTable("LanguageSecondarySource");
                });

            modelBuilder.Entity("LanguageWrittenSource", b =>
                {
                    b.Property<int>("TranslatedLanguagesId")
                        .HasColumnType("integer");

                    b.Property<int>("WrittenSourceId")
                        .HasColumnType("integer");

                    b.HasKey("TranslatedLanguagesId", "WrittenSourceId");

                    b.HasIndex("WrittenSourceId");

                    b.ToTable("LanguageWrittenSource");
                });

            modelBuilder.Entity("Mappa.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AlternateNames")
                        .HasColumnType("text[]");

                    b.Property<string>("AsciiName")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("GeoNamesId")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Mappa.Entities.Ethnicity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ethnicities");
                });

            modelBuilder.Entity("Mappa.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Mappa.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Mappa.Entities.IntraOrdinary", b =>
                {
                    b.Property<int>("PersonIdA")
                        .HasColumnType("integer");

                    b.Property<int>("PersonIdB")
                        .HasColumnType("integer");

                    b.HasKey("PersonIdA", "PersonIdB");

                    b.HasIndex("PersonIdB");

                    b.ToTable("IntraOrdinary");
                });

            modelBuilder.Entity("Mappa.Entities.IntraUnordinary", b =>
                {
                    b.Property<int>("PersonIdA")
                        .HasColumnType("integer");

                    b.Property<int>("PersonIdB")
                        .HasColumnType("integer");

                    b.HasKey("PersonIdA", "PersonIdB");

                    b.HasIndex("PersonIdB");

                    b.ToTable("IntraUnordinary");
                });

            modelBuilder.Entity("Mappa.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Mappa.Entities.OrdinaryPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateName")
                        .HasColumnType("text");

                    b.Property<int?>("BackgroundCityId")
                        .HasColumnType("integer");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<List<int>>("BirthYear")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("DeathYear")
                        .HasColumnType("integer[]");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionInTheSource")
                        .HasColumnType("text");

                    b.Property<int?>("EthnicityId")
                        .HasColumnType("integer");

                    b.Property<string>("ExplanationOfEthnicity")
                        .HasColumnType("text");

                    b.Property<int?>("FormerReligionId")
                        .HasColumnType("integer");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("InteractionWithOrdinaryExplanation")
                        .HasColumnType("text");

                    b.Property<string>("InteractionWithUnordinaryExplanation")
                        .HasColumnType("text");

                    b.Property<string>("InterestingFeature")
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProbableBirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("ProbableDeathYear")
                        .HasColumnType("integer");

                    b.Property<string>("ProfessionExplanation")
                        .HasColumnType("text");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("integer");

                    b.Property<string>("ReligionExplanation")
                        .HasColumnType("text");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundCityId");

                    b.HasIndex("EthnicityId");

                    b.HasIndex("FormerReligionId");

                    b.HasIndex("GenderId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("ReligionId");

                    b.ToTable("OrdinaryPersons");
                });

            modelBuilder.Entity("Mappa.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("Mappa.Entities.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("Mappa.Entities.SecondarySource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AlternateNames")
                        .HasColumnType("text[]");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("BibliographyInformation")
                        .HasColumnType("text");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("University")
                        .HasColumnType("text");

                    b.Property<int?>("YearWritten")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TypeId");

                    b.ToTable("SecondarySources");
                });

            modelBuilder.Entity("Mappa.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Mappa.Entities.UnordinaryPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateName")
                        .HasColumnType("text");

                    b.Property<int?>("BirthPlaceId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("BirthYear")
                        .HasColumnType("integer[]");

                    b.Property<int?>("DeathPlaceId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("DeathYear")
                        .HasColumnType("integer[]");

                    b.Property<string>("Depiction")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EthnicityId")
                        .HasColumnType("integer");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProbableBirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("ProbableDeathYear")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReligionId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirthPlaceId");

                    b.HasIndex("DeathPlaceId");

                    b.HasIndex("EthnicityId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("ReligionId1");

                    b.ToTable("UnordinaryPersons");
                });

            modelBuilder.Entity("Mappa.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mappa.Entities.WrittenSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AlternateNames")
                        .HasColumnType("text[]");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("KnownCopies")
                        .HasColumnType("text");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("LibraryInformation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("text");

                    b.Property<int?>("ProbableYearWritten")
                        .HasColumnType("integer");

                    b.Property<string>("RemarkableWorksOnTheBook")
                        .HasColumnType("text");

                    b.Property<string>("SurvivedCopies")
                        .HasColumnType("text");

                    b.Property<List<int>>("YearWritten")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("LanguageId");

                    b.ToTable("WrittenSources");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrdinaryPersonUnordinaryPerson", b =>
                {
                    b.Property<int>("InteractionsWithOrdinaryId")
                        .HasColumnType("integer");

                    b.Property<int>("InteractionsWithUnordinaryId")
                        .HasColumnType("integer");

                    b.HasKey("InteractionsWithOrdinaryId", "InteractionsWithUnordinaryId");

                    b.HasIndex("InteractionsWithUnordinaryId");

                    b.ToTable("OrdinaryPersonUnordinaryPerson");
                });

            modelBuilder.Entity("OrdinaryPersonWrittenSource", b =>
                {
                    b.Property<int>("OrdinaryPersonsId")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesId")
                        .HasColumnType("integer");

                    b.HasKey("OrdinaryPersonsId", "SourcesId");

                    b.HasIndex("SourcesId");

                    b.ToTable("OrdinaryPersonWrittenSource");
                });

            modelBuilder.Entity("UnordinaryPersonWrittenSource", b =>
                {
                    b.Property<int>("SourcesId")
                        .HasColumnType("integer");

                    b.Property<int>("UnordinaryPersonsId")
                        .HasColumnType("integer");

                    b.HasKey("SourcesId", "UnordinaryPersonsId");

                    b.HasIndex("UnordinaryPersonsId");

                    b.ToTable("UnordinaryPersonWrittenSource");
                });

            modelBuilder.Entity("CityWrittenSource", b =>
                {
                    b.HasOne("Mappa.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CitiesMentionedByTheSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.WrittenSource", null)
                        .WithMany()
                        .HasForeignKey("SourcesMentioningTheCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CityWrittenSource1", b =>
                {
                    b.HasOne("Mappa.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CitiesWhereSourcesAreWrittenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.WrittenSource", null)
                        .WithMany()
                        .HasForeignKey("SourcesWrittenInTheCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageSecondarySource", b =>
                {
                    b.HasOne("Mappa.Entities.SecondarySource", null)
                        .WithMany()
                        .HasForeignKey("SecondarySourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("TranslatedLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageWrittenSource", b =>
                {
                    b.HasOne("Mappa.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("TranslatedLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.WrittenSource", null)
                        .WithMany()
                        .HasForeignKey("WrittenSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mappa.Entities.IntraOrdinary", b =>
                {
                    b.HasOne("Mappa.Entities.OrdinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("PersonIdA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.OrdinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("PersonIdB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mappa.Entities.IntraUnordinary", b =>
                {
                    b.HasOne("Mappa.Entities.UnordinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("PersonIdA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.UnordinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("PersonIdB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mappa.Entities.OrdinaryPerson", b =>
                {
                    b.HasOne("Mappa.Entities.City", "BackgroundCity")
                        .WithMany("BackgroundCityOf")
                        .HasForeignKey("BackgroundCityId");

                    b.HasOne("Mappa.Entities.Ethnicity", "Ethnicity")
                        .WithMany()
                        .HasForeignKey("EthnicityId");

                    b.HasOne("Mappa.Entities.Religion", "FormerReligion")
                        .WithMany("FormerOrdinaryPersons")
                        .HasForeignKey("FormerReligionId");

                    b.HasOne("Mappa.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("Mappa.Entities.City", "Location")
                        .WithMany("LocationOf")
                        .HasForeignKey("LocationId");

                    b.HasOne("Mappa.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("Mappa.Entities.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.Navigation("BackgroundCity");

                    b.Navigation("Ethnicity");

                    b.Navigation("FormerReligion");

                    b.Navigation("Gender");

                    b.Navigation("Location");

                    b.Navigation("Profession");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("Mappa.Entities.SecondarySource", b =>
                {
                    b.HasOne("Mappa.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("Mappa.Entities.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Language");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Mappa.Entities.UnordinaryPerson", b =>
                {
                    b.HasOne("Mappa.Entities.City", "BirthPlace")
                        .WithMany("BirthPlaceOf")
                        .HasForeignKey("BirthPlaceId");

                    b.HasOne("Mappa.Entities.City", "DeathPlace")
                        .WithMany("DeathPlaceOf")
                        .HasForeignKey("DeathPlaceId");

                    b.HasOne("Mappa.Entities.Ethnicity", "Ethnicity")
                        .WithMany()
                        .HasForeignKey("EthnicityId");

                    b.HasOne("Mappa.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("Mappa.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("Mappa.Entities.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.HasOne("Mappa.Entities.Religion", null)
                        .WithMany("FormerUnordinaryPersons")
                        .HasForeignKey("ReligionId1");

                    b.Navigation("BirthPlace");

                    b.Navigation("DeathPlace");

                    b.Navigation("Ethnicity");

                    b.Navigation("Gender");

                    b.Navigation("Profession");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("Mappa.Entities.WrittenSource", b =>
                {
                    b.HasOne("Mappa.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("Mappa.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.Navigation("Genre");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mappa.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mappa.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mappa.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdinaryPersonUnordinaryPerson", b =>
                {
                    b.HasOne("Mappa.Entities.OrdinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("InteractionsWithOrdinaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.UnordinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("InteractionsWithUnordinaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdinaryPersonWrittenSource", b =>
                {
                    b.HasOne("Mappa.Entities.OrdinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("OrdinaryPersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.WrittenSource", null)
                        .WithMany()
                        .HasForeignKey("SourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UnordinaryPersonWrittenSource", b =>
                {
                    b.HasOne("Mappa.Entities.WrittenSource", null)
                        .WithMany()
                        .HasForeignKey("SourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mappa.Entities.UnordinaryPerson", null)
                        .WithMany()
                        .HasForeignKey("UnordinaryPersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mappa.Entities.City", b =>
                {
                    b.Navigation("BackgroundCityOf");

                    b.Navigation("BirthPlaceOf");

                    b.Navigation("DeathPlaceOf");

                    b.Navigation("LocationOf");
                });

            modelBuilder.Entity("Mappa.Entities.Religion", b =>
                {
                    b.Navigation("FormerOrdinaryPersons");

                    b.Navigation("FormerUnordinaryPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
