export enum Urls {
  Home = "/",
  About = "/about",
  ProjectHistory = "project-history",
  Contact = "/contact",
  Collaborations = "/collaborations",
  OrdinaryPeople = "/data/ordinary-people",
  UnordinaryPeople = "/data/unordinary-people",
  Sources = "/data/sources",
  Members = "/members",
  Publications = "/publications",
  Map = "/tools/map",
  MapTest = "/tools/map-test",
  SocialNetwork = "/tools/social-network",
}
